name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code # nombre del paso
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # que haga la busqueda en el historial de los commits

    - name: Docker login
      env: # variables de entonrno
        DOCKER_USER: ${{ secrets.DOCKER_USER }} # Secret user
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Secret password
      run: | # comandos a ejecutar
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login"
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
